rotten_ep3/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :games do
    resources :reviews, except: [:show, :index]
  end
  
  root 'games#index'
  

end

rotten_ep3/app/models/game.rb
class Game < ActiveRecord::Base
    belongs_to :user
    has_many :reviews

    has_attached_file :image, styles: { medium: "400x600#" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

rotten_ep3/app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :user
    belongs_to :games
end

rotten_ep3/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :games
  has_many :reviews, dependent: :destroy
end

rotten_ep3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rotten_ep3/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @reviews = Review.where(game_id: @game.id).order("created_at DESC")

    if @reviews.blank?
      @avg_review = 0;
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  # GET /games/new
  def new
    @game = current_user.games.build
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:nome, :descrição, :duração, :produtora, :avaliação, :image)
    end
end

rotten_ep3/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_game
  before_action :authenticate_user!

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.game_id = @game.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @game, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @game, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end
    
    def set_game
      @game = Game.find(params[:game_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

rotten_ep3/app/helpers/application_helper.rb
module ApplicationHelper
end

rotten_ep3/app/helpers/games_helper.rb
module GamesHelper
end

rotten_ep3/app/helpers/reviews_helper.rb
module ReviewsHelper
end

rotten_ep3/app/views/games/_form.html.erb
<%= form_for @game, html: { multipart: true } do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Title %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :descrição %>
  </div>
  <div class="field">
    <%= f.label :Length %><br>
    <%= f.text_field :duração %>
  </div>
  <div class="field">
    <%= f.label :Publisher %><br>
    <%= f.text_field :produtora %>
  </div>
  <div class="field">
    <%= f.label :Rating %><br>
    <%= f.text_field :avaliação %>
  </div>
  <div class="field">
  <%= f.label :image %><br>
  <%= f.file_field :image %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rotten_ep3/app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game, class: "btn btn-default" %> |
<%= link_to 'Back', games_path, class: "btn btn-default" %>

rotten_ep3/app/views/games/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Your Favorite Games Reviewed</h1>
    <p><%= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div class="row">
  <% @games.each do |game| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag game.image.url(:medium), class: 'image'), game %>
      </div>
    </div>
  <% end %>
</div>

rotten_ep3/app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path, class: "btn btn-default" %>

rotten_ep3/app/views/games/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @game.image.url(:medium) %>
        <div class="star-rating" data-score= <%= @avg_review %> ></div>
          <em><%= "#{@reviews.length} reviews" %></em>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @game.nome %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @game.descrição %></td>
              </tr>
              <tr>
                <td><strong>Game length:</strong></td>
                <td><%= @game.duração %></td>
              </tr>
              <tr>
                <td><strong>Publisher:</strong></td>
                <td><%= @game.produtora %></td>
              </tr>
              <tr>
                <td><strong>Rating:</strong></td>
                <td><%= @game.avaliação %></td>
              </tr>
           </tbody>
          </table>
          <%= link_to "write a Review", new_game_review_path(@game), class: "btn btn-danger" %>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="review title"><%= @game.nome %></h1>
        <p><%= @game.descrição %></p>

        <% if @reviews.blank? %>
          <h3>No reviews just yet, would you like to add the first?</h3>
          <%= link_to "write review", new_game_review_path(@game), class: "btn btn-danger"%>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="reviews">
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              <p><%= review.user.email.split('@')[0] %><%= ": " %><%=review.comment %></p> 
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%if user_signed_in? %>
  <% if current_user.admin %>
    <%= link_to 'Edit', edit_game_path(@game), class: "btn btn-default" %> |
    <%= link_to 'Destroy', @game, method: :delete, data: {confirm: 'Are you sure? This game is gonna be deleted!'}, class: "btn btn-default" %> |
    <%= link_to 'Back', games_path, class: "btn btn-default" %>
  <% else %>
    <%= link_to 'Back', games_path, class: "btn btn-default" %>
  <% end %>
<% else %>
  <%= link_to 'Back', games_path, class: "btn btn-default" %>
<% end %>

<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

rotten_ep3/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Rotten Sweet Potato", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "New Game", new_game_path, class: "active" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

rotten_ep3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenEp3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

rotten_ep3/app/views/reviews/_form.html.erb
<%= form_for([@game, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

rotten_ep3/app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Back', game_path(@game) %>

rotten_ep3/app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path, class: "btn btn-default" %>